/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sokoban;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JButton;

/**
 *
 * @author Jhoog_000
 */
public class Speelveld extends javax.swing.JPanel {
    private JButton start;
    private Muurvak muurvak;
    private Leegvak leegvak;
    private Eindvak eindvak;
    /**
     * Creates new form Speelveld
     */
    public Speelveld() {
       
        setup();
        initComponents();
    }
    
    public void setup(){
        this.setSize(new Dimension(600, 800));
        this.setBackground(Color.GREEN);
        
        
    }
    
     private int gridStructureLvl1[][] = {
           //0   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 2, 1, 2, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
            {1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    };
     int z=10;
     
     private void draw(Graphics g){
         int x=0;
         int y=50;
         
    for(int q = 0 ; q < 10; q++){
        x+=50;
        
        for(int w = 0; w < 10; w++){
        y+=50;
        if(y==550){
            y=50;
        }
            
    if(this.gridStructureLvl1[w][q] == 1)
    {   
        muurvak = new Muurvak(x,y,20,20);
        this.muurvak.zetX(x);
        this.muurvak.zetY(y);
        this.muurvak.zetBreedte(50);
        this.muurvak.zetHoogte(50);
        this.muurvak.paintComponent(g);
    }
    else if(this.gridStructureLvl1[w][q] == 2)
    {   
        leegvak = new Leegvak(x,y,20,20);
        this.leegvak.zetX(x);
        this.leegvak.zetY(y);
        this.leegvak.zetBreedte(50);
        this.leegvak.zetHoogte(50);
        this.leegvak.paintComponent(g);
    }
    
    }
}
    }
@Override
    public void paintComponent(Graphics g) {
        this.draw(g);
        requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
